### ISSUE TITLE
Broken Link In the Readme

### ISSUE THREAD

**Issue by bibbca** [singhularity/udacity_online_resume#1]
Under number 1 in the Readme is the link [Javascript Basics course](https://www.udacity.com/course/ud804).  I just stumbled across your repository and I wondered if you were aware.  Thanks!

**Comment by singhularity** [comment]
This code was written for a course a few years ago, the original link seems to have been moved :-)

**Comment by bibbca** [comment]
Oh, ok. Just making sure :)

**Comment by bibbca** [comment]
Okay, I'll close this issue then.
